spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30
    show-sql: true
    defer-datasource-initialization: false
  datasource:
    url: jdbc:postgresql://localhost:5438/audit-db?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: postgres
    password: root
  sql:
    init:
      mode: always
server:
  port: 8790
